blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/albertolicea00/my-wallet-ids-ios/discussions
    about: Ask questions or discuss ideas that are not a bug report or feature request.
